# tst_page.py
from bb_sys import TApplication
from bb_controls import TPage, TControl

# создаём приложение
app = TApplication()

# создаём страницу
p = TPage(app, "pgMain", "Tradition Core Demo")
p.style = app.base_style()

# добавляем контент
p.br(2)
p.h(1, "Tradition Core 2025 — HTML Generation Test")
p.h(2, "Sub Title")
p._tg("footer", "Generated by Tradition Core ⚙️")

# выводим результат
print(p.html())
